spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/kiwi
spring.datasource.username=kiwi
spring.datasource.password=kiwi_dev_password

spring.data.redis.host=localhost
spring.data.redis.port=6379
